# Skipping: AUTO, video config
paths:
    dataset: nerf_synthetic/lego
    train_json: nerf_synthetic/lego/transforms_train.json
    val_json: nerf_synthetic/lego/transforms_val.json
    test_json: nerf_synthetic/lego/transforms_test.json
    img_path: nerf_synthetic/lego/train/
    coarse_path: model/coarse/
    fine_path: model/fine/
    video_path: model/
img_features:
    img_width: 800
    img_height: 800
    near: 2.0
    far: 6.0
train:
    batch_size: 5
    l_coor: 8
    l_dir: 4
    dense_units: 256
    skip_layer: 4
    n_c: 64
    n_f: 128
    steps_per_epoch: 50
    validation_steps: 5
    epochs: 20
inference:
    sample_theta_points: 32
video:
    fps: 30
    quality: 10
    macro_block_size: 16
